# notebook
FROM jupyter/scipy-notebook

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
    && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get purge -y --auto-remove \
        software-properties-common \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        pkg-config \
        python3.5 \
        python3-dev \
        python3-pip \
        python3-setuptools \
        lib32ncurses5-dev \
        libfreetype6-dev \
        libpng-dev \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install the necessary packages in the virtual environment
RUN pip3 install \
    bitarray \
    dataset \
#    elasticsearch-dsl==2.0.0 \
    elasticsearch==7.0.0 \
    nltk \
    path.py

# Prebuild matplotlib font cache
# Otherwise the first time someone does this is a notebook, they'll see warning
# messages and have to wait.
RUN python -c "import matplotlib; matplotlib.use('TkAgg'); import matplotlib.pyplot"

COPY . /home/$NB_USER/work/

# Expect an elasticsearch server available at this host and port.
RUN sed -i "s/^\s*db_host\s*=.*$/db_host = 'elasticsearch'/" /home/$NB_USER/work/config.py
